"""CIFAR-100 split-into-tasks loader with LAMDA-PILOT class ordering.

Protocol refs:
    docs/protocols/fecam-router-gate.md v1.2.1
    §5.3 Upsampling:    32 -> 224 bicubic, antialias=True
    §5.4 Class ordering: LAMDA-PILOT default random permutation, seeded 1993
    §2.1 "DataLoader worker seeding": worker_init_fn=seed_worker + seeded generator
                                      (OR num_workers=0)
    §8.4 test 14         DataLoader RNG determinism.

Class order source: LAMDA-PILOT exps/cifar100_b0_inc10.json equivalent —
    order = np.random.RandomState(1993).shuffle(np.arange(100))
"""
from __future__ import annotations

from typing import List, Optional, Sequence, Tuple

import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset, Subset
from torchvision import datasets, transforms

from .utils import seed_worker


# ------------------------------------------------------------------
# Class ordering (LAMDA-PILOT convention)
# ------------------------------------------------------------------
def lamda_pilot_class_order(class_order_seed: int = 1993) -> List[int]:
    """Reproduces LAMDA-PILOT's canonical CIFAR-100 random permutation.

    The ordering shipped in LAMDA-PILOT exps/cifar100_b0_inc10.json is
    generated by `np.random.RandomState(1993).shuffle(np.arange(100))`.
    Deterministic regardless of the run seed.
    """
    rng = np.random.RandomState(class_order_seed)
    order = np.arange(100)
    rng.shuffle(order)
    return order.tolist()


def task_class_splits(class_order: Sequence[int], num_tasks: int,
                      classes_per_task: int) -> List[List[int]]:
    """Chunk class_order into num_tasks contiguous blocks of classes_per_task."""
    assert len(class_order) == num_tasks * classes_per_task, (
        f"class_order length {len(class_order)} != {num_tasks}*{classes_per_task}")
    return [list(class_order[t * classes_per_task:(t + 1) * classes_per_task])
            for t in range(num_tasks)]


# ------------------------------------------------------------------
# Transforms (§5.3)
# ------------------------------------------------------------------
def build_transforms(image_size: int = 224,
                     normalize_mean=(0.485, 0.456, 0.406),
                     normalize_std=(0.229, 0.224, 0.225)) -> transforms.Compose:
    """Bicubic 32->224 with antialias per §5.3. No augmentation per user-spec.

    NOTE: protocol §2.1 "Data augmentation" row calls for LAMDA-PILOT default
    (random crop + flip). User sprint brief pins "No augmentation". Matched
    across arms either way so does not bias A-vs-B.
    """
    return transforms.Compose([
        transforms.Resize(image_size,
                          interpolation=transforms.InterpolationMode.BICUBIC,
                          antialias=True),
        transforms.ToTensor(),
        transforms.Normalize(mean=list(normalize_mean), std=list(normalize_std)),
    ])


# ------------------------------------------------------------------
# Filtered subsets (reindex labels into local 0..classes_per_task-1 space
# AT CALL TIME via a label_map — does NOT rewrite dataset; keeps originals.)
# ------------------------------------------------------------------
class RemappedSubset(Dataset):
    """Wraps a torchvision dataset (or Subset) and remaps labels via label_map.

    label_map: dict mapping CIFAR-100 original class id -> new id (often the
    "task-local" id 0..C-1, or the global "seen-so-far" id 0..t*C-1).
    Samples whose original label is not in label_map are NOT skipped — the
    caller is responsible for passing only valid indices via Subset.
    """

    def __init__(self, base: Dataset, indices: Sequence[int],
                 label_map: dict):
        self.base = base
        self.indices = list(indices)
        self.label_map = label_map

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, i: int):
        x, y_orig = self.base[self.indices[i]]
        return x, self.label_map[int(y_orig)]


def _dataset_targets(ds) -> np.ndarray:
    """Return the label array for a torchvision CIFAR100 dataset."""
    targets = ds.targets if hasattr(ds, "targets") else [y for _, y in ds]
    return np.asarray(targets)


# ------------------------------------------------------------------
# Task-loader factory
# ------------------------------------------------------------------
def build_task_loaders(data_root: str, task_t: int,
                       class_order: Sequence[int],
                       classes_per_task: int,
                       batch_size: int = 128,
                       eval_batch_size: int = 256,
                       num_workers: int = 4,
                       pin_memory: bool = True,
                       seed: int = 42,
                       image_size: int = 224,
                       download: bool = True
                       ) -> Tuple[DataLoader, DataLoader, DataLoader, List[int]]:
    """Return (train_loader_t, test_loader_t, test_loader_seen_so_far, task_classes).

    - train_loader_t: training data from task t only (shuffled, seeded).
    - test_loader_t:  test data restricted to task-t classes (no shuffle).
    - test_loader_seen_so_far: test data restricted to all classes in tasks 0..t
      (no shuffle); used for §1.4 A_T "seen so far" evaluation.
    - task_classes: list of original CIFAR-100 class ids for task t.

    Labels returned by the loaders are GLOBAL ids: for class original_id `c`,
    the new id is `class_order.index(c)` so that eg. task 0 yields labels
    0..classes_per_task-1, task 1 yields classes_per_task..2*classes_per_task-1,
    etc. This keeps the classifier head a single Linear(d, num_tasks*classes_per_task).
    """
    tfm = build_transforms(image_size=image_size)
    train_ds = datasets.CIFAR100(root=data_root, train=True, download=download, transform=tfm)
    test_ds = datasets.CIFAR100(root=data_root, train=False, download=download, transform=tfm)

    task_classes = list(class_order[task_t * classes_per_task:(task_t + 1) * classes_per_task])
    seen_classes = list(class_order[: (task_t + 1) * classes_per_task])

    # Global label map: original CIFAR id -> position in class_order
    global_label_map = {int(c): int(i) for i, c in enumerate(class_order)}

    # Train subset = task-t classes
    train_targets = _dataset_targets(train_ds)
    train_mask = np.isin(train_targets, task_classes)
    train_indices = np.nonzero(train_mask)[0].tolist()
    train_subset = RemappedSubset(train_ds, train_indices, global_label_map)

    # Test subsets
    test_targets = _dataset_targets(test_ds)
    test_mask_t = np.isin(test_targets, task_classes)
    test_indices_t = np.nonzero(test_mask_t)[0].tolist()
    test_subset_t = RemappedSubset(test_ds, test_indices_t, global_label_map)

    test_mask_seen = np.isin(test_targets, seen_classes)
    test_indices_seen = np.nonzero(test_mask_seen)[0].tolist()
    test_subset_seen = RemappedSubset(test_ds, test_indices_seen, global_label_map)

    # Seeded generator for train shuffle (paired across arms by seed)
    g_train = torch.Generator().manual_seed(seed + 1000 * task_t)

    train_loader = DataLoader(
        train_subset, batch_size=batch_size, shuffle=True,
        num_workers=num_workers, pin_memory=pin_memory,
        worker_init_fn=seed_worker if num_workers > 0 else None,
        generator=g_train, drop_last=False,
    )
    test_loader_t = DataLoader(
        test_subset_t, batch_size=eval_batch_size, shuffle=False,
        num_workers=num_workers, pin_memory=pin_memory,
        worker_init_fn=seed_worker if num_workers > 0 else None,
    )
    test_loader_seen = DataLoader(
        test_subset_seen, batch_size=eval_batch_size, shuffle=False,
        num_workers=num_workers, pin_memory=pin_memory,
        worker_init_fn=seed_worker if num_workers > 0 else None,
    )

    return train_loader, test_loader_t, test_loader_seen, task_classes


def build_all_tests(data_root: str, class_order: Sequence[int],
                    eval_batch_size: int = 256, num_workers: int = 4,
                    pin_memory: bool = True, image_size: int = 224,
                    download: bool = True) -> DataLoader:
    """Final evaluation loader over ALL 100 classes. Used after the last task."""
    tfm = build_transforms(image_size=image_size)
    test_ds = datasets.CIFAR100(root=data_root, train=False, download=download, transform=tfm)
    global_label_map = {int(c): int(i) for i, c in enumerate(class_order)}
    indices = list(range(len(test_ds)))
    subset = RemappedSubset(test_ds, indices, global_label_map)
    return DataLoader(
        subset, batch_size=eval_batch_size, shuffle=False,
        num_workers=num_workers, pin_memory=pin_memory,
        worker_init_fn=seed_worker if num_workers > 0 else None,
    )
